language: java

jdk:
- oraclejdk8

cache:
  directories:
  - "$HOME/.m2/repository"

env:
  global:
  - secure: kQkJpWqGQ4yjmTMpqcXSfzBUNhOamAJQ15JzX+rQcsSXTkeXkPbWqQDcNf8ci26KmiEN+baVXlPGMiZhG7fWKngasyhCiWV62TLXzWiazAZeB/57w5sQwf5LAzMdsmcRhzyqA03Yi2ezg1fi9+QQarlEHHHyy563mOMRLk1tpxE=
  - secure: YgPynUE3ssWAgyKlUZeXZiU1IBZD6b4zXmXzkLLEq1MD5Xz4fwQDdhul117wC/nDJPwdjQSV7Ej3hVD20m10XL3thWchXE7vWfXve06D7Tc6dutE2iPlPtTPzYqyQbNR+DU7W76CQPmvCh2Dlyu1ih+oNHsZ5wM7pVN/R1QUClk=

script:
- mvn -DfailOnServiceError=false clean jacoco:prepare-agent test deploy jacoco:report
  coveralls:report --settings travis-maven-settings.xml
